events {
    worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name localhost;

    # Root User App (No basePath needed here usually)
    location / {
      proxy_pass http://user-web:3000;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    # Admin App
    location /admin {
      proxy_pass http://admin-web:3000; # Removed the trailing slash
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    # Vendor App
    location /vendor {
      proxy_pass http://vendor-web:3000; # Removed the trailing slash
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    # Driver App
    location /driver {
      proxy_pass http://driver-web:3000; # Removed the trailing slash
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }
  }
}